version: '3.8'

services:
  linkedin-bot:
    build: .
    volumes:
      - ./data:/app/data
      - ./messages.json:/app/messages.json
      - ./chrome:/root/.config/google-chrome
    environment:
      - DISPLAY=:99
    stdin_open: true
    tty: true
